dist: focal
sudo: true
language: python

matrix:
  include:
  - python: 3.9
    name: "Python39"

before_install:
  - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
  - sudo apt-get -y install graphviz
  - pip uninstall -y shapely
  - pip install --no-binary shapely shapely

install:
  - pip install wheel pyquicksetup
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python setup.py unittests
