name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  build_wheels:
    name: Build documentation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      #- name: Install
      #  run: python -m pip install -e .
      - name: Copy license
        run: cp LICENSE* ./_doc/sphinxdoc/source
      - name: Copy readme
        run: cp README* ./_doc/sphinxdoc/source

      #- name: Documentation
      #  run: python -m sphinx ./_doc/sphinxdoc/source ./dist/html
      - name: Documentation
        run: python setup.py build_sphinx

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/html/**
